name: Aggregate

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - run: julia --project=. -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/control-toolbox/ct-registry.git"));' 
      # - uses: julia-actions/add-julia-registry@v1
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     registry: control-toolbox/ct-registry
      - uses: julia-actions/julia-buildpkg@v1
        with:
          version: '1.9'
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=src/ -e "CTDocs.jl"
        
